# Generated by Django 4.1.3 on 2023-02-21 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "rus_description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("q_ty", models.IntegerField(blank=True, default=1, null=True)),
                ("lead_time", models.CharField(blank=True, max_length=50, null=True)),
                ("etd", models.CharField(blank=True, max_length=50, null=True)),
                ("eta", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "delivery_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("order_id", models.CharField(max_length=50)),
                ("manager", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Менеджер, которому принадлежит заказ",
                    ),
                ),
            ],
        ),
    ]
