# Generated by Django 4.1.3 on 2023-02-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="user",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="orders",
            name="q_ty",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
