# Generated by Django 4.1.3 on 2023-02-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0002_rename_user_orders_user_id_alter_orders_q_ty"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="user_id",
            new_name="user",
        ),
    ]
