# Generated by Django 4.1.3 on 2023-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("datacenter", "0003_rename_user_id_orders_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="email",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
